let badges_names = [
        'blocked',
        'bot-variant',
        'bot',
        'channel',
        'group-incognito',
        'group-invite',
        'group-private',
        'group-public',
        'mobile',
        'rss-variant',
        'rss',
        'server'
    ],
    material_icons = [
        'palette',
        'pinned',
        'pinned-circle-small',
        'saved-messages',
        'translate',
        'trash',
        'circles',
        'crosshairs-gps',
        'crosshairs-question',
        'crosshairs',
        'trash',
        'client',
        'client-outline',
        'database-lock',
        'index',
        'bug',
        'cloud',
        'key',
        'account',
        'alert-circle',
        'map-marker-outline',
        'map-marker',
        'minus',
        'account-outline',
        'birthday',
        'birthday-outline',
        'status',
        'status-outline',
        'job',
        'job-outline',
        'address',
        'address-outline',
        'email',
        'email-outline',
        'description',
        'description-outline',
        'contact-add',
        'check',
        'call-outline',
        'call',
        'search',
        'device-cellphone',
        'device-console',
        'device-desktop',
        'device-tablet',
        'device-web',
        'devices',
        'web',
        'bell',
        'bell-off',
        'bell-sleep',
        'cancel',
        'edit',
        'edit-outline',
        'check-circle',
        'blocked-add',
        'information',
        'information-outline',
        'qrcode',
        'fullname',
        'fullname-outline',
        'id-outline',
        'clock-outline',
        'index',
        'restrictions-outline',
        'history',
        'camera-retake',
        'chevron-down',
        'membership-outline',
        'invite-outline',
        'chevron-right-variant',
        'chevron-left-variant',
        'subscription-to',
        'subscription-from',
        'image',
        'xmpp',
        'file-audio',
        'file-video',
        'file-document',
        'file-presentation',
        'file-zip',
        'file',
        'file-pdf',
        'close',
        'link',
        'security',
        'picture-in-picture-minimize',
        'picture-in-picture-bottom-right',
        'picture-in-picture-top-right',
        'pause',
        'volume-off',
        'volume-high',
        'video',
        'plus',
        'play',
        'player-float',
        'player-full',
        'player-mini-variant',
        'player-mini',
        'message-bookmark-outline',
    ],
    circle_icons = [,
        'task'
    ],
    fs = require('fs');
badges_names.forEach((name) => {
    let svg = fs.readFileSync(`../xabber-icons/badge/icon/${name}.svg`, 'utf-8');
    svg = svg.replace(/<title>.*<\/title>/, '');
    svg = svg.replaceAll('24px', '100%');
    svg = svg.replaceAll('16px', '100%');
    fs.writeFileSync(`./templates/svg/${name}.html`, svg);
});
material_icons.forEach((name) => {
    let svg = fs.readFileSync(`../xabber-icons/icon/material/${name}.svg`, 'utf-8');
    svg = svg.replace(/<title>.*<\/title>/, '');
    svg = svg.replaceAll('24px', '100%');
    svg = svg.replaceAll('16px', '100%');
    fs.writeFileSync(`./templates/svg/${name}.html`, svg);
});
circle_icons.forEach((name) => {
    let svg = fs.readFileSync(`../xabber-icons/badge/circle/${name}.svg`, 'utf-8');
    svg = svg.replace(/<title>.*<\/title>/, '');
    svg = svg.replaceAll('24px', '100%');
    svg = svg.replaceAll('16px', '100%');
    fs.writeFileSync(`./templates/svg/${name}.html`, svg);
});