// only external libs and plugins for them
define([
    "backbone",
    "underscore",
    "jquery",
    "moment",
    "wavesurfer",
    "slug",
    "sha256",
    "magnific-popup",
    "i18next",
    "i18next-post",
    "strophe",
    "Plyr",
    "Quill",
    "libsignal-protocol",
    "sha1_hasher",
    "~/css/color-scheme.css",
    "~/css/materialdesignicons.css",
    "~/css/materialize.css",
    "~/css/plyr.css",
    "~/css/quill.snow.css",
    "~/css/xabber.css",
    "~/node_modules/magnific-popup/dist/magnific-popup.css",
    "~/node_modules/perfect-scrollbar/dist/css/perfect-scrollbar.css",
    "strophe.disco",
    "strophe.ping",
    "strophe.rsm",
    "strophe.caps",
    "strophe.pubsub",
    "omemo",
    "backbone.localsync",
    "sha1_hasher",
    "materialize",
    "qrcode",
    "perfectScrollbarJQuery"
], function(Backbone, _, $, moment, WaveSurfer, slug, sha256, magnificPopup, i18next, i18next_sprintf, Strophe, plyr, Quill, libsignal, sha1) {
    return _.extend({
        $: $,
        _: _,
        ol: ol,
        moment: moment,
        WaveSurfer: WaveSurfer,
        Plyr: plyr,
        Quill: Quill,
        libsignal: libsignal,
        slug: slug,
        sha1: sha1,
        xabber_i18next: i18next,
        xabber_i18next_sprintf: i18next_sprintf,
        sha256: sha256,
        magnificPopup: magnificPopup,
        Strophe: Strophe
    }, Strophe);
});
